---
- name: "Installing & configuring Wordpress using GIT"
  hosts: amazon
  become: true
  vars_files:
    - conf.vars
    - secret.vars


        
  tasks:
    
    
    - name: "Apache - package Installation"
      yum:
        name: httpd
        state: present
       
    - name: "Apache - Crating VirtualHost /etc/httpd/conf.d/default.conf"
      template:
        src: virualhost.conf.j2
        dest: /etc/httpd/conf.d/default.conf
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"


    - name: "Apache - Creating DocumentRoot /var/www/html/"
      file:
        path: "/var/www/html/"
        state: directory
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"

    - name: "Apache - Installing php support"
      shell: amazon-linux-extras install php7.4 -y


    - name: "Apache - Restarting/Enabling php-fpm"
      service:
        name: php-fpm
        state: restarted
        enabled: true


    - name: "Apache - Restarting/Enabling Service"
      service:
        name: httpd
        state: restarted
        enabled: true
    - name: "Wordpress - Downloading Archive File {{ wp_url }}"
      get_url:
        url: "{{ wp_url }}"
        dest: /tmp/wordpress.tar.gz
            
    - name: "Wordpress - Extracting /tmp/wordpress.tar.gz"
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: true
            
    - name: "Wordpress - Copying Contents from /tmp/wordpress/ to /var/www/html/"
      copy:
        src: /tmp/wordpress/
        dest: "/var/www/html/"
        remote_src: true
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"
            
    - name: "Wordpress - Creating wp-config.php from template"
      template:
        src: wp-config.php.j2
        dest: "/var/www/html/wp-config.php"
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"
            
    - name: "Post-Installation CleanUp"
      file:
        path: "{{ item}}"
        state: absent
      with_items:
        - /tmp/wordpres.tar.gz
        - /tmp/wordpress

